[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8FF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
runOnSave = false